import type { PromptPreset } from '../types/preset'

export const PRESETS: PromptPreset[] = [
  // ─── A. Render Node (Main Renderer) ───
  {
    id: 'screen-to-render',
    name: 'Screen to render',
    icon: 'screen-to-render',
    category: 'render',
    applicableNodeTypes: ['RENDER'],
    mergeMode: 'replace',
    basePrompt: 'Create photorealistic image',
    negativePrompt: 'cartoon, illustration, sketch, low quality, blurry',
    visualConstraints: 'Preserve exact geometry, camera angle, and spatial layout from the source image.',
    forbiddenChanges: 'Do not add or remove architectural elements. Do not change room proportions.',
  },
  {
    id: 'image-to-sketch',
    name: 'Image to sketch',
    icon: 'image-to-sketch',
    category: 'render',
    applicableNodeTypes: ['RENDER'],
    mergeMode: 'replace',
    basePrompt: 'Convert to architectural sketch drawing',
    negativePrompt: 'photorealistic, photograph, color photo',
    visualConstraints: 'Maintain architectural proportions and perspective.',
    forbiddenChanges: 'Do not alter building geometry.',
  },
  {
    id: 'top-view',
    name: 'Top view',
    icon: 'top-view',
    category: 'render',
    applicableNodeTypes: ['RENDER'],
    mergeMode: 'replace',
    basePrompt: 'Generate top-down orthographic view',
    negativePrompt: 'perspective distortion, vanishing point, angled view',
    visualConstraints: "Bird's eye view, parallel projection.",
    forbiddenChanges: 'Do not add perspective.',
  },
  {
    id: 'side-view',
    name: 'Side view',
    icon: 'side-view',
    category: 'render',
    applicableNodeTypes: ['RENDER'],
    mergeMode: 'replace',
    basePrompt: 'Generate side elevation view',
    negativePrompt: 'top view, perspective, aerial',
    visualConstraints: 'Orthographic side elevation.',
    forbiddenChanges: 'Do not rotate the viewpoint.',
  },
  {
    id: 'another-view',
    name: 'Another view',
    icon: 'another-view',
    category: 'render',
    applicableNodeTypes: ['RENDER'],
    mergeMode: 'replace',
    basePrompt: 'Generate an alternative camera angle of the same scene',
    negativePrompt: 'identical angle, same viewpoint',
    visualConstraints: 'Maintain the same room, furniture, and style.',
    forbiddenChanges: 'Do not change the interior design or objects.',
  },

  // ─── B. Modifier Node (Details Editor) ───
  {
    id: 'enhance-realism',
    name: 'Enhance realism',
    icon: 'enhance-realism',
    category: 'modifier',
    applicableNodeTypes: ['MODIFIER'],
    mergeMode: 'replace',
    basePrompt: 'Photorealistic architectural visualization. Enhance material realism, global illumination, reflections, and micro-details. Natural lighting, physically based rendering quality.',
    negativePrompt: 'cartoon, illustration, low quality, oversaturated',
    visualConstraints: 'Preserve exact geometry, camera angle, and object placement.',
    forbiddenChanges: 'Do NOT add or remove objects. Do NOT change room layout or furniture positions.',
  },
  {
    id: 'volumetric-rays',
    name: 'Volumetric rays',
    icon: 'volumetric-rays',
    category: 'modifier',
    applicableNodeTypes: ['MODIFIER'],
    mergeMode: 'replace',
    basePrompt: 'Add cinematic volumetric light rays. Sunlight scattering through space with realistic atmospheric particles. Soft god rays.',
    negativePrompt: 'overexposure, dramatic color shift, artificial lighting, harsh shadows',
    visualConstraints: 'Preserve all geometry and composition.',
    forbiddenChanges: 'Do NOT change lighting direction. Do NOT alter room geometry.',
  },
  {
    id: 'make-brighter',
    name: 'Make brighter',
    icon: 'make-brighter',
    category: 'modifier',
    applicableNodeTypes: ['MODIFIER'],
    mergeMode: 'replace',
    basePrompt: 'Increase overall exposure and brightness. Preserve color balance and material fidelity.',
    negativePrompt: 'blown highlights, overexposure, washed out, color shift',
    visualConstraints: 'Maintain original lighting direction and shadow positions.',
    forbiddenChanges: 'Do NOT change lighting direction, color temperature, or shadow geometry.',
  },
  {
    id: 'closeup',
    name: 'Closeup',
    icon: 'closeup',
    category: 'modifier',
    applicableNodeTypes: ['MODIFIER'],
    mergeMode: 'replace',
    basePrompt: 'Create a close-up shot of the main subject. Shallow depth of field, realistic lens compression. Focus on material detail and texture quality.',
    negativePrompt: 'wide angle, distant view, blurry subject, unfocused',
    visualConstraints: 'Maintain original style and lighting.',
    forbiddenChanges: 'Do NOT change materials or style.',
  },
  {
    id: 'axonometry',
    name: 'Axonometry',
    icon: 'axonometry',
    category: 'modifier',
    applicableNodeTypes: ['MODIFIER'],
    mergeMode: 'replace',
    basePrompt: 'Generate axonometric architectural visualization. Parallel projection. Clean edges, neutral lighting, technical clarity.',
    negativePrompt: 'perspective distortion, vanishing point, artistic, painterly',
    visualConstraints: 'No perspective distortion.',
    forbiddenChanges: 'Do NOT add artistic effects or stylization.',
  },
  {
    id: 'winter',
    name: 'Winter',
    icon: 'winter',
    category: 'modifier',
    applicableNodeTypes: ['MODIFIER'],
    mergeMode: 'replace',
    basePrompt: 'Change season to winter. Snow accumulation on horizontal surfaces. Cold daylight atmosphere. Bare trees, frost on windows.',
    negativePrompt: 'summer, green foliage, warm tones, sunny',
    visualConstraints: 'Preserve architecture and camera position.',
    forbiddenChanges: 'Do NOT change building geometry or camera angle.',
  },
  {
    id: 'autumn',
    name: 'Autumn',
    icon: 'autumn',
    category: 'modifier',
    applicableNodeTypes: ['MODIFIER'],
    mergeMode: 'replace',
    basePrompt: 'Change season to autumn. Warm golden and orange foliage. Soft warm-toned daylight.',
    negativePrompt: 'winter, snow, summer green, cold tones',
    visualConstraints: 'Preserve architecture and camera position.',
    forbiddenChanges: 'Do NOT change building geometry or camera angle.',
  },
  {
    id: 'technical-drawings',
    name: 'Technical drawings',
    icon: 'technical-drawings',
    category: 'modifier',
    applicableNodeTypes: ['MODIFIER'],
    mergeMode: 'replace',
    basePrompt: 'Architectural technical drawing style. Monochrome or limited color palette. Clear linework, no artistic shading. Orthographic or axonometric projection.',
    negativePrompt: 'photorealistic, color photo, artistic, painterly, textures',
    visualConstraints: 'Maintain exact proportions and dimensions.',
    forbiddenChanges: 'Do NOT add artistic effects. Do NOT add color beyond line weights.',
  },
  {
    id: 'logo',
    name: 'Logo',
    icon: 'logo',
    category: 'modifier',
    applicableNodeTypes: ['MODIFIER'],
    mergeMode: 'replace',
    basePrompt: 'Transform the image into a clean logo-style illustration. Flat colors, simplified shapes. Transparent or white background.',
    negativePrompt: 'photorealistic, textures, lighting effects, gradients, shadows',
    visualConstraints: 'Simplified geometric shapes.',
    forbiddenChanges: 'Do NOT preserve photorealistic textures.',
  },
  {
    id: 'day-to-night',
    name: 'Day to night',
    icon: 'day-to-night',
    category: 'modifier',
    applicableNodeTypes: ['MODIFIER'],
    mergeMode: 'replace',
    basePrompt: 'Convert daytime scene to nighttime. Artificial lighting visible from interior. Natural night sky illumination. Warm window glow.',
    negativePrompt: 'daylight, sunny, bright sky, daytime',
    visualConstraints: 'Preserve geometry and composition.',
    forbiddenChanges: 'Do NOT change building geometry or furniture.',
  },
  {
    id: 'night-to-day',
    name: 'Night to day',
    icon: 'night-to-day',
    category: 'modifier',
    applicableNodeTypes: ['MODIFIER'],
    mergeMode: 'replace',
    basePrompt: 'Convert nighttime scene to daytime. Natural daylight illumination. Clear or partly cloudy sky.',
    negativePrompt: 'night, dark, artificial lighting only, stars',
    visualConstraints: 'Preserve geometry and composition.',
    forbiddenChanges: 'Do NOT change building geometry or furniture.',
  },
  {
    id: 'add-people',
    name: 'Add people',
    icon: 'add-people',
    category: 'modifier',
    applicableNodeTypes: ['MODIFIER'],
    mergeMode: 'replace',
    basePrompt: 'Add realistic people naturally integrated into the scene. Correct scale, perspective, and lighting. People should not block key architectural elements.',
    negativePrompt: 'mannequins, cartoon people, oversized, floating',
    visualConstraints: 'Match lighting and perspective of the existing scene.',
    forbiddenChanges: 'Do NOT alter architecture or furniture.',
  },
  {
    id: 'add-blurred-people',
    name: 'Add blurred people',
    icon: 'add-blurred-people',
    category: 'modifier',
    applicableNodeTypes: ['MODIFIER'],
    mergeMode: 'replace',
    basePrompt: 'Add motion-blurred people for realism. Long exposure effect. People walking naturally through the space.',
    negativePrompt: 'sharp people, static poses, mannequins',
    visualConstraints: 'Match lighting and perspective.',
    forbiddenChanges: 'Do NOT alter architecture or furniture.',
  },
  {
    id: 'add-blurred-cars',
    name: 'Add blurred cars',
    icon: 'add-blurred-cars',
    category: 'modifier',
    applicableNodeTypes: ['MODIFIER'],
    mergeMode: 'replace',
    basePrompt: 'Add motion-blurred cars on roads. Long exposure effect for dynamic movement.',
    negativePrompt: 'static cars, parked, sharp focus on vehicles',
    visualConstraints: 'Match road perspective and scene scale.',
    forbiddenChanges: 'Do NOT alter buildings or landscape.',
  },
  {
    id: 'add-cars',
    name: 'Add cars',
    icon: 'add-cars',
    category: 'modifier',
    applicableNodeTypes: ['MODIFIER'],
    mergeMode: 'replace',
    basePrompt: 'Add realistic parked cars matching scene context. Correct scale and perspective.',
    negativePrompt: 'floating cars, oversized, cartoon',
    visualConstraints: 'Match lighting and perspective.',
    forbiddenChanges: 'Do NOT alter buildings.',
  },
  {
    id: 'add-flowers',
    name: 'Add flowers',
    icon: 'add-flowers',
    category: 'modifier',
    applicableNodeTypes: ['MODIFIER'],
    mergeMode: 'replace',
    basePrompt: 'Add natural flowers subtly integrated into the scene. Respect scale, season, and climate.',
    negativePrompt: 'oversized flowers, artificial, plastic',
    visualConstraints: 'Do not obstruct architecture.',
    forbiddenChanges: 'Do NOT change architecture or major scene elements.',
  },
  {
    id: 'add-grass',
    name: 'Add grass',
    icon: 'add-grass',
    category: 'modifier',
    applicableNodeTypes: ['MODIFIER'],
    mergeMode: 'replace',
    basePrompt: 'Add natural grass and ground cover. Realistic lawn texture, appropriate for the climate.',
    negativePrompt: 'artificial turf, oversaturated green, unrealistic',
    visualConstraints: 'Match terrain and scene context.',
    forbiddenChanges: 'Do NOT change architecture or hardscape.',
  },
  {
    id: 'add-trees',
    name: 'Add trees',
    icon: 'add-trees',
    category: 'modifier',
    applicableNodeTypes: ['MODIFIER'],
    mergeMode: 'replace',
    basePrompt: 'Add realistic trees appropriate to the climate and scene. Correct scale and natural placement.',
    negativePrompt: 'cartoon trees, floating, oversized, indoor trees outside',
    visualConstraints: 'Match season and climate.',
    forbiddenChanges: 'Do NOT obstruct key architectural views.',
  },

  // ─── C. Upscale Node ───
  {
    id: 'upscale',
    name: 'Upscale',
    icon: 'upscale',
    category: 'upscale',
    applicableNodeTypes: ['UPSCALE'],
    mergeMode: 'replace',
    basePrompt: 'Upscale',
    negativePrompt: '',
    visualConstraints: 'Preserve all details from original.',
    forbiddenChanges: 'Do NOT alter content or composition.',
  },

  // ─── D. Video Node ───
  {
    id: 'zoom-in-video',
    name: 'Zoom in',
    icon: 'zoom-in-video',
    category: 'video',
    applicableNodeTypes: ['VIDEO'],
    mergeMode: 'replace',
    basePrompt: 'Zoom in',
    negativePrompt: '',
    visualConstraints: 'Smooth camera motion.',
    forbiddenChanges: 'Do NOT change scene content.',
  },
  {
    id: 'move-forward',
    name: 'Move forward',
    icon: 'move-forward',
    category: 'video',
    applicableNodeTypes: ['VIDEO'],
    mergeMode: 'replace',
    basePrompt: 'Move forward',
    negativePrompt: '',
    visualConstraints: 'Smooth forward dolly motion.',
    forbiddenChanges: 'Do NOT change scene content.',
  },
  {
    id: 'orbit',
    name: 'Orbit',
    icon: 'orbit',
    category: 'video',
    applicableNodeTypes: ['VIDEO'],
    mergeMode: 'replace',
    basePrompt: 'Orbit camera around subject',
    negativePrompt: '',
    visualConstraints: 'Smooth orbital motion.',
    forbiddenChanges: 'Do NOT change scene content.',
  },
  {
    id: 'pan-left',
    name: 'Pan left',
    icon: 'pan-left',
    category: 'video',
    applicableNodeTypes: ['VIDEO'],
    mergeMode: 'replace',
    basePrompt: 'Pan camera left',
    negativePrompt: '',
    visualConstraints: 'Smooth lateral motion.',
    forbiddenChanges: 'Do NOT change scene content.',
  },
]

export function getPresetsForNodeType(nodeType: string): PromptPreset[] {
  return PRESETS.filter((p) => p.applicableNodeTypes.includes(nodeType as PromptPreset['applicableNodeTypes'][number]))
}

export function getPresetById(id: string): PromptPreset | undefined {
  return PRESETS.find((p) => p.id === id)
}
