// NanoBanana - Prompt Presets Data
var nodePresets = {
  render: [
    { id: 'screen-to-render', name: 'Screen to render', mergeMode: 'replace', prompt: 'Create photorealistic image', negative: 'cartoon, illustration, sketch, low quality, blurry', visualConstraints: 'Preserve exact geometry, camera angle, and spatial layout from the source image.', forbiddenChanges: 'Do not add or remove architectural elements. Do not change room proportions.' },
    { id: 'image-to-sketch', name: 'Image to sketch', mergeMode: 'replace', prompt: 'Convert to architectural sketch drawing', negative: 'photorealistic, photograph, color photo', visualConstraints: 'Maintain architectural proportions and perspective.', forbiddenChanges: 'Do not alter building geometry.' },
    { id: 'top-view', name: 'Top view', mergeMode: 'replace', prompt: 'Generate top-down orthographic view', negative: 'perspective distortion, vanishing point, angled view', visualConstraints: "Bird's eye view, parallel projection.", forbiddenChanges: 'Do not add perspective.' },
    { id: 'side-view', name: 'Side view', mergeMode: 'replace', prompt: 'Generate side elevation view', negative: 'top view, perspective, aerial', visualConstraints: 'Orthographic side elevation.', forbiddenChanges: 'Do not rotate the viewpoint.' },
    { id: 'another-view', name: 'Another view', mergeMode: 'replace', prompt: 'Generate an alternative camera angle of the same scene', negative: 'identical angle, same viewpoint', visualConstraints: 'Maintain the same room, furniture, and style.', forbiddenChanges: 'Do not change the interior design or objects.' }
  ],
  modifier: [
    { id: 'enhance-realism', name: 'Enhance realism', mergeMode: 'replace', prompt: 'Photorealistic architectural visualization. Enhance material realism, global illumination, reflections, and micro-details. Natural lighting, physically based rendering quality.', negative: 'cartoon, illustration, low quality, oversaturated', visualConstraints: 'Preserve exact geometry, camera angle, and object placement.', forbiddenChanges: 'Do NOT add or remove objects. Do NOT change room layout or furniture positions.' },
    { id: 'volumetric-rays', name: 'Volumetric rays', mergeMode: 'replace', prompt: 'Add cinematic volumetric light rays. Sunlight scattering through space with realistic atmospheric particles. Soft god rays.', negative: 'overexposure, dramatic color shift, artificial lighting, harsh shadows', visualConstraints: 'Preserve all geometry and composition.', forbiddenChanges: 'Do NOT change lighting direction. Do NOT alter room geometry.' },
    { id: 'make-brighter', name: 'Make brighter', mergeMode: 'replace', prompt: 'Increase overall exposure and brightness. Preserve color balance and material fidelity.', negative: 'blown highlights, overexposure, washed out, color shift', visualConstraints: 'Maintain original lighting direction and shadow positions.', forbiddenChanges: 'Do NOT change lighting direction, color temperature, or shadow geometry.' },
    { id: 'closeup', name: 'Closeup', mergeMode: 'replace', prompt: 'Create a close-up shot of the main subject. Shallow depth of field, realistic lens compression. Focus on material detail and texture quality.', negative: 'wide angle, distant view, blurry subject, unfocused', visualConstraints: 'Maintain original style and lighting.', forbiddenChanges: 'Do NOT change materials or style.' },
    { id: 'axonometry', name: 'Axonometry', mergeMode: 'replace', prompt: 'Generate axonometric architectural visualization. Parallel projection. Clean edges, neutral lighting, technical clarity.', negative: 'perspective distortion, vanishing point, artistic, painterly', visualConstraints: 'No perspective distortion.', forbiddenChanges: 'Do NOT add artistic effects or stylization.' },
    { id: 'winter', name: 'Winter', mergeMode: 'replace', prompt: 'Change season to winter. Snow accumulation on horizontal surfaces. Cold daylight atmosphere. Bare trees, frost on windows.', negative: 'summer, green foliage, warm tones, sunny', visualConstraints: 'Preserve architecture and camera position.', forbiddenChanges: 'Do NOT change building geometry or camera angle.' },
    { id: 'autumn', name: 'Autumn', mergeMode: 'replace', prompt: 'Change season to autumn. Warm golden and orange foliage. Soft warm-toned daylight.', negative: 'winter, snow, summer green, cold tones', visualConstraints: 'Preserve architecture and camera position.', forbiddenChanges: 'Do NOT change building geometry or camera angle.' },
    { id: 'technical-drawings', name: 'Technical drawings', mergeMode: 'replace', prompt: 'Architectural technical drawing style. Monochrome or limited color palette. Clear linework, no artistic shading. Orthographic or axonometric projection.', negative: 'photorealistic, color photo, artistic, painterly, textures', visualConstraints: 'Maintain exact proportions and dimensions.', forbiddenChanges: 'Do NOT add artistic effects. Do NOT add color beyond line weights.' },
    { id: 'logo', name: 'Logo', mergeMode: 'replace', prompt: 'Transform the image into a clean logo-style illustration. Flat colors, simplified shapes. Transparent or white background.', negative: 'photorealistic, textures, lighting effects, gradients, shadows', visualConstraints: 'Simplified geometric shapes.', forbiddenChanges: 'Do NOT preserve photorealistic textures.' },
    { id: 'day-to-night', name: 'Day to night', mergeMode: 'replace', prompt: 'Convert daytime scene to nighttime. Artificial lighting visible from interior. Natural night sky illumination. Warm window glow.', negative: 'daylight, sunny, bright sky, daytime', visualConstraints: 'Preserve geometry and composition.', forbiddenChanges: 'Do NOT change building geometry or furniture.' },
    { id: 'night-to-day', name: 'Night to day', mergeMode: 'replace', prompt: 'Convert nighttime scene to daytime. Natural daylight illumination. Clear or partly cloudy sky.', negative: 'night, dark, artificial lighting only, stars', visualConstraints: 'Preserve geometry and composition.', forbiddenChanges: 'Do NOT change building geometry or furniture.' },
    { id: 'add-people', name: 'Add people', mergeMode: 'replace', prompt: 'Add realistic people naturally integrated into the scene. Correct scale, perspective, and lighting. People should not block key architectural elements.', negative: 'mannequins, cartoon people, oversized, floating', visualConstraints: 'Match lighting and perspective of the existing scene.', forbiddenChanges: 'Do NOT alter architecture or furniture.' },
    { id: 'add-blurred-people', name: 'Add blurred people', mergeMode: 'replace', prompt: 'Add motion-blurred people for realism. Long exposure effect. People walking naturally through the space.', negative: 'sharp people, static poses, mannequins', visualConstraints: 'Match lighting and perspective.', forbiddenChanges: 'Do NOT alter architecture or furniture.' },
    { id: 'add-blurred-cars', name: 'Add blurred cars', mergeMode: 'replace', prompt: 'Add motion-blurred cars on roads. Long exposure effect for dynamic movement.', negative: 'static cars, parked, sharp focus on vehicles', visualConstraints: 'Match road perspective and scene scale.', forbiddenChanges: 'Do NOT alter buildings or landscape.' },
    { id: 'add-cars', name: 'Add cars', mergeMode: 'replace', prompt: 'Add realistic parked cars matching scene context. Correct scale and perspective.', negative: 'floating cars, oversized, cartoon', visualConstraints: 'Match lighting and perspective.', forbiddenChanges: 'Do NOT alter buildings.' },
    { id: 'add-flowers', name: 'Add flowers', mergeMode: 'replace', prompt: 'Add natural flowers subtly integrated into the scene. Respect scale, season, and climate.', negative: 'oversized flowers, artificial, plastic', visualConstraints: 'Do not obstruct architecture.', forbiddenChanges: 'Do NOT change architecture or major scene elements.' },
    { id: 'add-grass', name: 'Add grass', mergeMode: 'replace', prompt: 'Add natural grass and ground cover. Realistic lawn texture, appropriate for the climate.', negative: 'artificial turf, oversaturated green, unrealistic', visualConstraints: 'Match terrain and scene context.', forbiddenChanges: 'Do NOT change architecture or hardscape.' },
    { id: 'add-trees', name: 'Add trees', mergeMode: 'replace', prompt: 'Add realistic trees appropriate to the climate and scene. Correct scale and natural placement.', negative: 'cartoon trees, floating, oversized, indoor trees outside', visualConstraints: 'Match season and climate.', forbiddenChanges: 'Do NOT obstruct key architectural views.' }
  ],
  upscale: [
    { id: 'upscale', name: 'Upscale', mergeMode: 'replace', prompt: 'Upscale', negative: '', visualConstraints: 'Preserve all details from original.', forbiddenChanges: 'Do NOT alter content or composition.' }
  ],
  video: [
    { id: 'zoom-in', name: 'Zoom in', mergeMode: 'replace', prompt: 'Zoom in', negative: '', visualConstraints: 'Smooth camera motion.', forbiddenChanges: 'Do NOT change scene content.' },
    { id: 'move-forward', name: 'Move forward', mergeMode: 'replace', prompt: 'Move forward', negative: '', visualConstraints: 'Smooth forward dolly motion.', forbiddenChanges: 'Do NOT change scene content.' },
    { id: 'orbit', name: 'Orbit', mergeMode: 'replace', prompt: 'Orbit camera around subject', negative: '', visualConstraints: 'Smooth orbital motion.', forbiddenChanges: 'Do NOT change scene content.' },
    { id: 'pan-left', name: 'Pan left', mergeMode: 'replace', prompt: 'Pan camera left', negative: '', visualConstraints: 'Smooth lateral motion.', forbiddenChanges: 'Do NOT change scene content.' }
  ]
};
